namespace ShimmyMySherbet.MySQL.EF.Models
{
    public enum EConnectionFailiureReason : int
    {
        UNKNOWN = ~0,
        SUCCESS = ~1,
        TOO_MANY_CONNECTIONS = 1040,
        BAD_HOST_ADDR = 1042,
        BAD_HANDSHAKE = 1043,
        ACCESS_DENIED = 1044,
        ACCESS_DENIED_PASSWORD = 1045,
        NO_DATABASE_SELECTED = 1046,
        UNKNOWN_DATABASE = 1049,
        SERVER_SHUTDOWN = 1053,
        IP_SOCKET_FAIL = 1081,
        ACCESS_DENIED_NO_PASSWORD = 1698,
        SWITCH_USER_ACCESS_DENIED = 1873,
        ACCESS_DENIED_ACCOUNT_LOCKED = 3118,
        ACCESS_DENIED_DATABASE = 3879,
        ACCESS_DENIED_CONSECUTIVE_FAILED_LOGINS
    }
}